server:
  port: 12001

logging:
  level:
    root: error
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org:
      hibernate:
        cache: info
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
    jdbc:
      sqlonly: fatal
      resultsettable: info
      sqltiming: info
      audit: fatal
      resultset: fatal
      connection: fatal
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_oauth?useSSL=true
    username: root
    password: FwYoB4Bwx38BPuI4
  jpa:
    #initialize from resources after hibernate
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        #! identation des requetes dans le log
        format_sql: true
        hbm2ddl:
          #allow sql insert with multiple lines into import.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
