server:
  port: 12001

logging:
  level:
    jdbc:
      sqlonly: fatal
      resultsettable: info
      sqltiming: info
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework: debug
      hibernate:
        cache: info
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #h2 with a file, on windows C:\Users\username\h2 databases
    url: jdbc:h2:file:~/h2 databases/oauth2;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        #! identation des requetes dans le log
        format_sql: true
        hbm2ddl:
          #allow sql insert with multiple lines into import.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor